{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mrmodder",
    "module": "YetAnotherModLibrary",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "YetAnotherModLibrary-0.3.1.jar",
          "url": "YetAnotherModLibrary-0.3.1.jar",
          "size": 28674,
          "sha512": "bd95bee389da692084faba3c83cf8901e9128d5c33ff7bd1723b2060d6f6ee608466dc6068c72aa83ee4131b12d71fe31c9e7a9191486391576c51c8e92fc274",
          "sha256": "b47322469846132ba43866680a7c8c511a05048c5e9a294adc39f0811e97ea6d",
          "sha1": "51fb3f2daf4937d677db0cfa4c4d4b8fdbef3427",
          "md5": "d1d2f695e417860431a668223989fd19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "YetAnotherModLibrary-0.3.1.jar",
          "url": "YetAnotherModLibrary-0.3.1.jar",
          "size": 28674,
          "sha512": "bd95bee389da692084faba3c83cf8901e9128d5c33ff7bd1723b2060d6f6ee608466dc6068c72aa83ee4131b12d71fe31c9e7a9191486391576c51c8e92fc274",
          "sha256": "b47322469846132ba43866680a7c8c511a05048c5e9a294adc39f0811e97ea6d",
          "sha1": "51fb3f2daf4937d677db0cfa4c4d4b8fdbef3427",
          "md5": "d1d2f695e417860431a668223989fd19"
        }
      ]
    }
  ]
}
